### ISSUE TITLE
求HBase书籍

### ISSUE THREAD

**Issue by Shmilyqjj** [SummerJoan3/books#4]
求HBase书籍

**Comment by SummerJoan3** [comment]
> 求HBase书籍
已添加
1. HBase 实战
2. HBase 不睡觉书
3. HBase 权威指南

**Comment by SummerJoan3** [comment]
> > 求HBase书籍
> > 已添加
> 
> 1. HBase 实战
> 2. HBase 不睡觉书
> 3. HBase 权威指南

**Comment by SummerJoan3** [comment]
> 求HBase书籍

已添加
1. HBase 实战
2. HBase 不睡觉书
3. HBase 权威指南
