### ISSUE TITLE
求《数据密集型应用系统设计》中文版

### ISSUE THREAD

**Issue by Shmilyqjj** [SummerJoan3/books#5]
求《数据密集型应用系统设计》中文版

**Comment by SummerJoan3** [comment]
> 求《数据密集型应用系统设计》中文版

已添加
- 数据密集型应用系统设计,297m,链接: [https://pan.baidu.com/s/1ClZNlKmdWFKY2BWNrA4vDw](https://pan.baidu.com/s/1ClZNlKmdWFKY2BWNrA4vDw), 提取码: nr4k

**Comment by Shmilyqjj** [comment]
万分感谢
