### ISSUE TITLE
links failed.

### ISSUE THREAD

**Issue by noisnemid** [SummerJoan3/books#7]
精通 Python 设计模式

Python 深度学习实战：75 个有关神经网络建模、强化学习与迁移学习的解决方案,

智能信息融合与目标识别方法

机器智能：人工情感

无人机简史

人工智能技术

具体数学 计算机科学基础(第 2 版)

**Comment by SummerJoan3** [comment]
精通 Python 设计模式,智能信息融合与目标识别方法, 具体数学 计算机科学基础(第 2 版)已修复,其他的太容易和谐了,我再想想办法@noisnemid

**Comment by SummerJoan3** [comment]
@noisnemid 加我网盘好友,发条消息,我直接共享给你,我账号: 安仁坊全

**Comment by noisnemid** [comment]
@SummerJoan3  已加，请通过，感谢！

**Comment by SummerJoan3** [comment]
@noisnemid 已分享
