### ISSUE TITLE
link failed

### ISSUE THREAD

**Issue by Jorgezz** [SummerJoan3/books#8]
未来简史,链接: https://pan.baidu.com/s/1ZOt4v6_g8ORn9jSe3Fjh6w 提取码: mtjm

**Comment by SummerJoan3** [comment]
@Jorgezz https://image.xjq.icu/2021/3/8/2021.3.8-%E6%9C%AA%E6%9D%A5%E7%AE%80%E5%8F%B2.epub,已更新，只有epub格式，点击链接直接下载

**Comment by SummerJoan3** [comment]
@Jorgezz 已更新，只有epub格式，点击链接直接下载，https://image.xjq.icu/2021/3/8/2021.3.8-%E6%9C%AA%E6%9D%A5%E7%AE%80%E5%8F%B2.epub
